import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import data from '../data.json';
import './style.css';

const STORAGE_KEY='notion-finance-demo-v3';
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0);
const monthKey=date=>date?.slice(0,7)||'';
const addMonths=(date,offset)=>{const d=new Date(`${date}T12:00:00`);d.setMonth(d.getMonth()+offset);return d.toISOString().slice(0,10)};
const monthLabel=key=>{const [y,m]=key.split('-');return new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric'}).format(new Date(Number(y),Number(m)-1,1)).toUpperCase()};
const navItems=[['Inicio','⌂'],['Movimientos','▣'],['Presupuesto mensual','▦'],['Gastos programados','◫'],['Categorías','◎'],['Cuentas','◈']];
const seedState={records:(data.records||[]).map((r,i)=>({...r,id:r.id||`seed-${i}`})),scheduled:data.scheduled||[],categories:data.categories||[],accounts:data.accounts||[],lastRun:data.lastRun||''};
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?{...seedState,...JSON.parse(raw)}:seedState}catch{return seedState}}
function totals(records){const income=records.filter(r=>r.type==='Ingreso').reduce((s,r)=>s+Number(r.amount||0),0);const expenses=records.filter(r=>r.type==='Gasto').reduce((s,r)=>s+Number(r.amount||0),0);const savings=records.filter(r=>r.type==='Ahorro').reduce((s,r)=>s+Number(r.amount||0),0);return {income,expenses,savings,balance:income-expenses-savings}}
function newMovement(date='2026-04-01'){return {name:'',date,amount:'',type:'Gasto',account:'Tarjeta Demo',subcategory:'Compras',category:'Hogar',status:'Pendiente',inInstallments:false,installments:6,firstInstallmentDate:date}}
function newScheduled(){return {id:'',name:'',amount:'',day:5,category:'Hogar',account:'Cuenta Corriente',active:true}}

function App(){
 const [store,setStore]=useState(loadState);const [page,setPage]=useState('Inicio');const [view,setView]=useState('Todos');const [selectedMonth,setSelectedMonth]=useState('2026-04');const [editor,setEditor]=useState(null);const [scheduledEditor,setScheduledEditor]=useState(null);const [entity,setEntity]=useState(null);const [toast,setToast]=useState('');const [mobileOpen,setMobileOpen]=useState(false);const [running,setRunning]=useState(false);const [automationStep,setAutomationStep]=useState(-1);
 useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(store)),[store]);
 const records=store.records||[];const filtered=useMemo(()=>records.filter(r=>view==='Todos'||(view==='Ingresos'&&r.type==='Ingreso')||(view==='Gastos'&&r.type==='Gasto')||(view==='Cuotas'&&r.installment)),[records,view]);
 const monthKeys=useMemo(()=>{const set=new Set(records.map(r=>monthKey(r.date)));set.add(selectedMonth);return [...set].filter(Boolean).sort()},[records,selectedMonth]);
 const flash=msg=>{setToast(msg);setTimeout(()=>setToast(''),2200)};const openPage=p=>{setPage(p);setMobileOpen(false)};
 const resetDemo=()=>{localStorage.removeItem(STORAGE_KEY);setStore(seedState);setPage('Inicio');setView('Todos');setSelectedMonth('2026-04');setEntity(null);setEditor(null);flash('Demo restablecida')};
 const saveMovement=form=>{const amount=Number(form.amount)||0;if(form.type==='Gasto'&&form.inInstallments&&Number(form.installments)>1&&!form.id){const count=Math.max(2,Math.min(36,Number(form.installments)||2));const first=form.firstInstallmentDate||form.date;const base=Math.floor(amount/count);const remainder=amount-base*count;const generated=Array.from({length:count},(_,i)=>({...form,id:`cuota-${Date.now()}-${i}`,name:`${form.name} ${i+1}/${count}`,date:addMonths(first,i),amount:base+(i===count-1?remainder:0),installment:true,installmentIndex:i+1,installmentCount:count,inInstallments:false,status:'Pendiente'}));setStore(s=>({...s,records:[...s.records,...generated]}));setSelectedMonth(monthKey(first));setEditor(null);flash(`${count} cuotas distribuidas por mes`);return;}const item={...form,amount,id:form.id||`mov-${Date.now()}`,firstInstallmentDate:form.firstInstallmentDate||form.date};setStore(s=>({...s,records:form.id?s.records.map(r=>r.id===form.id?item:r):[...s.records,item]}));setSelectedMonth(monthKey(item.date));setEditor(null);setEntity(null);flash(form.id?'Movimiento actualizado':'Movimiento creado')};
 const saveScheduled=form=>{const item={...form,amount:Number(form.amount)||0,day:Number(form.day)||1,id:form.id||`scheduled-${Date.now()}`};setStore(s=>({...s,scheduled:form.id?s.scheduled.map(x=>x.id===form.id?item:x):[...s.scheduled,item]}));setScheduledEditor(null);flash('Gasto programado guardado')};
 const runAutomation=()=>{if(running)return;setRunning(true);setAutomationStep(0);[1,2,3,4,5].forEach((step,i)=>setTimeout(()=>setAutomationStep(step),(i+1)*550));setTimeout(()=>{const next=addMonths(`${selectedMonth}-01`,1).slice(0,7);const [y,m]=next.split('-');setStore(s=>{const salary=s.records.some(r=>monthKey(r.date)===next&&r.demoAutomation&&r.type==='Ingreso')?[]:[{id:`auto-salary-${Date.now()}`,name:'Sueldo programado',date:`${next}-01`,amount:950000,type:'Ingreso',account:'Cuenta Corriente',subcategory:'Sueldo',category:'Finanzas',status:'Generado',demoAutomation:true}];const recurring=s.scheduled.filter(x=>x.active).filter(x=>!s.records.some(r=>monthKey(r.date)===next&&r.scheduledId===x.id)).map((x,i)=>({id:`auto-rec-${Date.now()}-${i}`,name:x.name,date:`${y}-${m}-${String(Math.min(28,x.day)).padStart(2,'0')}`,amount:x.amount,type:'Gasto',account:x.account,subcategory:'Programado',category:x.category,status:'Replicado',scheduledId:x.id,demoAutomation:true}));return {...s,records:[...s.records,...salary,...recurring],lastRun:new Date().toLocaleString('es-CL')}});setSelectedMonth(next);setRunning(false);flash(`Período ${monthLabel(next)} preparado`)},3300)};
 return <div className="notion-shell"><button className="mobile-menu" onClick={()=>setMobileOpen(v=>!v)}>☰</button><aside className={mobileOpen?'open':''}><button className="workspace" onClick={()=>openPage('Inicio')}>◆ Gestión Financiera</button><nav>{navItems.map(([label,icon])=><button key={label} className={page===label?'active':''} onClick={()=>openPage(label)}>{icon} {label}</button>)}</nav><button className="reset" onClick={resetDemo}>↺ Restablecer demo</button><div className="aside-note">Demo pública<br/><small>Sin credenciales · datos ficticios</small></div></aside><main><div className="cover"><div className="cover-copy"><span>PLANTILLA DE NOTION</span><strong>Gestión Financiera Mensual</strong><small>Automatiza · organiza · controla</small></div><div className="plant">🌿</div></div><div className="page">{page==='Inicio'&&<Home records={records} scheduled={store.scheduled} onOpen={openPage} onNew={()=>setEditor(newMovement(`${selectedMonth}-01`))}/>} {page==='Movimientos'&&<Movements records={filtered} allRecords={records} view={view} setView={setView} onNew={()=>setEditor(newMovement(`${selectedMonth}-01`))} onOpen={r=>setEntity({kind:'movement',data:r})}/>} {page==='Presupuesto mensual'&&<Budget records={records} filtered={filtered} view={view} setView={setView} selectedMonth={selectedMonth} setSelectedMonth={setSelectedMonth} months={monthKeys} onNew={()=>setEditor(newMovement(`${selectedMonth}-01`))} onOpen={r=>setEntity({kind:'movement',data:r})} running={running} step={automationStep} run={runAutomation}/>} {page==='Gastos programados'&&<Scheduled items={store.scheduled} onNew={()=>setScheduledEditor(newScheduled())} onOpen={x=>setScheduledEditor({...x})}/>} {page==='Categorías'&&<Categories items={store.categories} onOpen={x=>setEntity({kind:'category',data:x})}/>} {page==='Cuentas'&&<Accounts items={store.accounts} records={records} onOpen={x=>setEntity({kind:'account',data:x})}/>}</div></main>{editor&&<MovementEditor draft={editor} categories={store.categories} accounts={store.accounts} onClose={()=>setEditor(null)} onSave={saveMovement}/>} {scheduledEditor&&<ScheduledEditor draft={scheduledEditor} categories={store.categories} accounts={store.accounts} onClose={()=>setScheduledEditor(null)} onSave={saveScheduled}/>} {entity&&<EntityPanel entity={entity} onClose={()=>setEntity(null)} onEdit={entity.kind==='movement'?()=>setEditor({...entity.data}):null}/>} {toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Summary({records}){const t=totals(records);return <div className="summary"><div><span>Ingresos</span><b className="positive">+ {money(t.income)}</b></div><div><span>Gastos</span><b className="negative">− {money(t.expenses)}</b></div><div className="balance"><span>Disponible</span><b>{money(t.balance)}</b><small>{money(t.income)} − {money(t.expenses)}{t.savings?` − ${money(t.savings)} ahorro`:''}</small></div><div><span>Cuotas pendientes</span><b>{records.filter(r=>r.installment&&r.status!=='Pagado').length}</b></div></div>}
function Home({records,scheduled,onOpen,onNew}){const current=records.filter(r=>monthKey(r.date)==='2026-04');const t=totals(current);return <><div className="emoji">🏠</div><div className="page-head"><div><h1>Inicio</h1><p>Una mini réplica interactiva de Notion para probar la plantilla financiera sin conectar ningún workspace real.</p></div><button onClick={onNew}>+ Nueva página</button></div><Summary records={current}/><div className="dashboard">{[['Presupuesto mensual',`${money(t.balance)} disponible`],['Movimientos',`${records.length} registros`],['Gastos programados',`${scheduled.filter(x=>x.active).length} reglas activas`],['Categorías','Clasificación de movimientos'],['Cuentas','Saldos calculados']].map(([a,b])=><button key={a} onClick={()=>onOpen(a)}><b>{a}</b><span>{b}</span></button>)}</div></>}
function ViewTabs({view,setView}){return <div className="views">{['Todos','Ingresos','Gastos','Cuotas'].map(v=><button key={v} className={view===v?'view-active':''} onClick={()=>setView(v)}>{v}</button>)}</div>}
function Movements({records,allRecords,view,setView,onNew,onOpen}){return <><div className="emoji">▣</div><div className="page-head"><div><h1>Movimientos</h1><p>Base de datos interactiva con ingresos, gastos, ahorros y cuotas.</p></div><button onClick={onNew}>Nuevo ▾</button></div><Summary records={allRecords}/><ViewTabs view={view} setView={setView}/><Database records={records} onOpen={onOpen} onNew={onNew}/></>}
function Budget({records,filtered,view,setView,selectedMonth,setSelectedMonth,months,onNew,onOpen,running,step,run}){const monthRecords=records.filter(r=>monthKey(r.date)===selectedMonth);const shown=filtered.filter(r=>monthKey(r.date)===selectedMonth);const idx=months.indexOf(selectedMonth);const prev=months[idx-1]||addMonths(`${selectedMonth}-01`,-1).slice(0,7);const next=months[idx+1]||addMonths(`${selectedMonth}-01`,1).slice(0,7);return <><div className="emoji">💸</div><div className="page-head"><div><h1>Presupuesto mensual</h1><p>Los totales se calculan desde los movimientos del período. Cada cuota impacta solo el mes que le corresponde.</p></div><button onClick={run} disabled={running}>{running?'Ejecutando…':'Ejecutar demostración'}</button></div><div className="period-nav"><button onClick={()=>setSelectedMonth(prev)}>←</button><strong>{monthLabel(selectedMonth)}</strong><button onClick={()=>setSelectedMonth(next)}>→</button></div><Summary records={monthRecords}/><ViewTabs view={view} setView={setView}/><Database records={shown} onOpen={onOpen} onNew={onNew}/><Automation running={running} step={step}/></>}
function Database({records,onOpen,onNew}){return <div className="database-wrap"><div className="database"><div className="row head"><span>Aa Nombre</span><span>Fecha</span><span>Monto</span><span>Tipo</span><span>Cargo / Cuenta</span><span>Subcategoría</span><span>Categoría general</span><span>Cuotas</span><span>Estado</span></div>{records.map(r=><button className="row data-row" key={r.id} onClick={()=>onOpen(r)}><span className="title">📄 {r.name}</span><span>{r.date}</span><span className={r.type==='Ingreso'?'amount-in':'amount-out'}>{r.type==='Ingreso'?'+ ':'− '}{money(r.amount)}</span><span><i className={`tag ${r.type.toLowerCase()}`}>{r.type}</i></span><span>{r.account}</span><span>{r.subcategory||'—'}</span><span><i className="category">{r.category}</i></span><span>{r.installment?`${r.installmentIndex}/${r.installmentCount}`:'—'}</span><span>{r.status}</span></button>)}<button className="new-row" onClick={onNew}>+ Nueva página</button></div></div>}
function Automation({running,step}){const labels=['Creando período...','Registrando ingreso programado...','Replicando gastos...','Generando cuotas...','Actualizando estados...'];return <section className="automation-log"><h2>⚙️ Automatización mensual simulada</h2><p>Representa visualmente lo que realizan los scripts Python del repositorio, pero sin conectarse a Notion.</p><div className="progress-list">{labels.map((x,i)=><div key={x} className={step>i?'done':running&&step===i?'active':''}><span>{step>i?'✓':running&&step===i?'…':'○'}</span>{x}</div>)}</div></section>}
function Scheduled({items,onNew,onOpen}){return <><div className="emoji">◫</div><div className="page-head"><div><h1>Gastos programados</h1><p>Reglas recurrentes que se replican al ejecutar la automatización mensual.</p></div><button onClick={onNew}>Nuevo</button></div><div className="simple-table"><div className="simple-head"><span>Nombre</span><span>Monto</span><span>Día de cobro</span><span>Categoría</span><span>Cuenta</span><span>Activo</span></div>{items.map(x=><button key={x.id} onClick={()=>onOpen(x)}><span>{x.name}</span><span>{money(x.amount)}</span><span>{x.day}</span><span>{x.category}</span><span>{x.account}</span><span>{x.active?'Sí':'No'}</span></button>)}<button className="new-row" onClick={onNew}>+ Nueva página</button></div></>}
function Categories({items,onOpen}){return <><div className="emoji">◎</div><div className="page-head"><div><h1>Categorías</h1><p>Base simple de clasificación para relacionar movimientos.</p></div></div><div className="gallery">{items.map(x=><button key={x.name} onClick={()=>onOpen(x)}><span>{x.icon||'◌'}</span><b>{x.name}</b><small>{x.description||'Categoría de demo'}</small></button>)}</div></>}
function Accounts({items,records,onOpen}){const balanceFor=a=>{const rel=records.filter(r=>r.account===a.name);return Number(a.openingBalance||0)+rel.filter(r=>r.type==='Ingreso').reduce((s,r)=>s+r.amount,0)-rel.filter(r=>r.type==='Gasto'||r.type==='Ahorro').reduce((s,r)=>s+r.amount,0)};return <><div className="emoji">◈</div><div className="page-head"><div><h1>Cuentas</h1><p>Saldos ficticios calculados con los movimientos visibles de la demo.</p></div></div><div className="account-grid">{items.map(a=><button key={a.name} onClick={()=>onOpen({...a,computedBalance:balanceFor(a)})}><span>{a.name}</span><b>{money(balanceFor(a))}</b><small>{a.kind||'Cuenta ficticia'}</small></button>)}</div></>}
function EntityPanel({entity,onClose,onEdit}){const d=entity.data;return <div className="overlay" onMouseDown={onClose}><div className="editor read-panel" onMouseDown={e=>e.stopPropagation()}><div className="editor-top"><span>↗ Página</span><button onClick={onClose}>×</button></div><div className="editor-icon">📄</div><h2>{d.name}</h2>{entity.kind==='movement'?<div className="properties">{[['Fecha',d.date],['Monto',money(d.amount)],['Tipo',d.type],['Cuenta',d.account],['Subcategoría',d.subcategory||'—'],['Categoría',d.category],['Cuotas',d.installment?`${d.installmentIndex}/${d.installmentCount}`:'—'],['Estado',d.status]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>:<div className="properties">{Object.entries(d).filter(([k])=>!['name','description','icon'].includes(k)).map(([a,b])=><div key={a}><span>{a}</span><b>{typeof b==='number'?money(b):String(b)}</b></div>)}</div>}{d.description&&<p className="page-copy">{d.description}</p>}{onEdit&&<div className="editor-actions"><button className="primary" onClick={onEdit}>Editar página</button></div>}</div></div>}
function MovementEditor({draft,categories,accounts,onClose,onSave}){const [f,setF]=useState(draft);const set=(k,v)=>setF(s=>({...s,[k]:v}));const preview=f.type==='Gasto'&&f.inInstallments?Math.round((Number(f.amount)||0)/(Number(f.installments)||1)):0;return <div className="overlay" onMouseDown={onClose}><div className="editor" onMouseDown={e=>e.stopPropagation()}><div className="editor-top"><span>↗ Página de movimiento</span><button onClick={onClose}>×</button></div><div className="editor-icon">📄</div><input className="title-input" placeholder="Sin título" value={f.name} onChange={e=>set('name',e.target.value)}/><div className="editor-props"><Field label="Fecha"><input type="date" value={f.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Monto"><input type="number" value={f.amount} onChange={e=>set('amount',e.target.value)}/></Field><Field label="Tipo"><select value={f.type} onChange={e=>set('type',e.target.value)}><option>Ingreso</option><option>Gasto</option><option>Ahorro</option></select></Field><Field label="Cuenta"><select value={f.account} onChange={e=>set('account',e.target.value)}>{accounts.map(a=><option key={a.name}>{a.name}</option>)}</select></Field><Field label="Subcategoría"><input value={f.subcategory||''} onChange={e=>set('subcategory',e.target.value)}/></Field><Field label="Categoría"><select value={f.category} onChange={e=>set('category',e.target.value)}>{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></Field><Field label="Estado"><select value={f.status} onChange={e=>set('status',e.target.value)}><option>Pendiente</option><option>Pagado</option><option>Preparado</option></select></Field>{f.type==='Gasto'&&<Field label="Compra en cuotas"><input type="checkbox" checked={!!f.inInstallments} onChange={e=>set('inInstallments',e.target.checked)}/></Field>}{f.type==='Gasto'&&f.inInstallments&&<><Field label="Número de cuotas"><input type="number" min="2" max="36" value={f.installments} onChange={e=>set('installments',e.target.value)}/></Field><Field label="Primera cuota"><input type="date" value={f.firstInstallmentDate||f.date} onChange={e=>set('firstInstallmentDate',e.target.value)}/></Field></>}</div>{preview>0&&<div className="installment-preview"><b>{f.installments} cuotas de aprox. {money(preview)}</b><span>Se crearán una por mes desde {f.firstInstallmentDate||f.date}.</span></div>}<div className="editor-actions"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.name||!f.date||!Number(f.amount)} onClick={()=>onSave(f)}>Guardar</button></div></div></div>}
function ScheduledEditor({draft,categories,accounts,onClose,onSave}){const [f,setF]=useState(draft);const set=(k,v)=>setF(s=>({...s,[k]:v}));return <div className="overlay" onMouseDown={onClose}><div className="editor" onMouseDown={e=>e.stopPropagation()}><div className="editor-top"><span>↗ Gasto programado</span><button onClick={onClose}>×</button></div><div className="editor-icon">📄</div><input className="title-input" placeholder="Sin título" value={f.name} onChange={e=>set('name',e.target.value)}/><div className="editor-props"><Field label="Monto"><input type="number" value={f.amount} onChange={e=>set('amount',e.target.value)}/></Field><Field label="Día de cobro"><input type="number" min="1" max="28" value={f.day} onChange={e=>set('day',e.target.value)}/></Field><Field label="Categoría"><select value={f.category} onChange={e=>set('category',e.target.value)}>{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></Field><Field label="Cuenta"><select value={f.account} onChange={e=>set('account',e.target.value)}>{accounts.map(a=><option key={a.name}>{a.name}</option>)}</select></Field><Field label="Activo"><input type="checkbox" checked={!!f.active} onChange={e=>set('active',e.target.checked)}/></Field></div><div className="editor-actions"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.name||!Number(f.amount)} onClick={()=>onSave(f)}>Guardar</button></div></div></div>}
function Field({label,children}){return <label><span>{label}</span>{children}</label>}
createRoot(document.getElementById('root')).render(<App/>);
